'use client';

import { useState } from 'react';
import { useDashboardStore } from '@/hooks/use-dashboard-store';
import { useWebSocket } from '@/hooks/use-websocket';

interface ExecutionPlanProps {
  projectId: string;
}

/** @description Displays the execution plan generated by planner-agent (Layer 0).
 * Subscribes to plan:generated WebSocket event and renders collapsible agent sections. */
export function ExecutionPlan({ projectId }: ExecutionPlanProps) {
  const executionPlan = useDashboardStore((s) => s.executionPlan);
  const agents = useDashboardStore((s) => s.agents);
  useWebSocket({ projectId });

  if (!executionPlan) {
    return (
      <div className="flex flex-col items-center justify-center py-12 text-center text-[var(--text-tertiary)]">
        <p className="text-sm">El plan de ejecución se generará cuando el pipeline inicie.</p>
      </div>
    );
  }

  // Parse sections from markdown: split on ## headings
  const sections = parsePlanSections(executionPlan);

  return (
    <div className="space-y-3">
      {sections.map((section) => {
        const agentDone = agents.some(
          (a) => a.status === 'done' && section.title.toLowerCase().includes(a.type),
        );
        return (
          <PlanSection key={section.title} section={section} completed={agentDone} />
        );
      })}
    </div>
  );
}

interface PlanSectionData {
  title: string;
  content: string;
}

function parsePlanSections(markdown: string): PlanSectionData[] {
  const lines = markdown.split('\n');
  const sections: PlanSectionData[] = [];
  let current: PlanSectionData | null = null;

  for (const line of lines) {
    if (line.startsWith('## ')) {
      if (current) sections.push(current);
      current = { title: line.replace(/^## /, ''), content: '' };
    } else if (current) {
      current.content += line + '\n';
    }
  }
  if (current) sections.push(current);
  return sections;
}

function PlanSection({ section, completed }: { section: PlanSectionData; completed: boolean }) {
  const [open, setOpen] = useState(false);

  return (
    <div className="glass-card rounded-xl overflow-hidden">
      <button
        type="button"
        onClick={() => setOpen(!open)}
        className="w-full flex items-center gap-3 px-4 py-3 text-left hover:bg-[var(--bg-secondary)] transition-colors"
      >
        <span className={`text-sm ${completed ? 'text-green-400' : 'text-[var(--text-tertiary)]'}`}>
          {completed ? '✓' : '○'}
        </span>
        <span className="flex-1 text-sm font-medium text-[var(--text-primary)]">
          {section.title}
        </span>
        <span className="text-xs text-[var(--text-tertiary)]">{open ? '▲' : '▼'}</span>
      </button>
      {open && (
        <div className="px-4 pb-4 text-sm text-[var(--text-secondary)] whitespace-pre-wrap border-t border-[var(--muted-border)]">
          {section.content.trim()}
        </div>
      )}
    </div>
  );
}
