import fs from 'node:fs/promises';
import path from 'node:path';
import prisma from '../lib/prisma.js';
import { extractCriteria } from './criteria-extractor.js';

const TOKEN_BUDGET_CHARS = 160_000; // ~40K tokens at 4 chars/token
const LARGE_FILE_CHARS = 10 * 1_024; // 10KB threshold for summarization
const SUMMARY_HEAD_LINES = 50;
const SUMMARY_TAIL_LINES = 20;

/**
 * @description Reads a project's spec.md from the filesystem (generated by the spec engine).
 */
async function readSpecMd(projectDir: string): Promise<string> {
  try {
    return await fs.readFile(path.join(projectDir, 'spec.md'), 'utf8');
  } catch {
    try {
      return await fs.readFile(path.join(projectDir, 'README.md'), 'utf8');
    } catch {
      return '(no spec.md found)';
    }
  }
}

/**
 * @description Lists all files under `dir`, returning paths relative to rootDir.
 */
async function listAllFiles(dir: string, rootDir: string): Promise<string[]> {
  const result: string[] = [];
  try {
    const entries = await fs.readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      const abs = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        result.push(...(await listAllFiles(abs, rootDir)));
      } else {
        result.push(path.relative(rootDir, abs));
      }
    }
  } catch {
    // Directory may not exist yet
  }
  return result;
}

/**
 * @description Returns a condensed version of a file: first 50 + last 20 lines.
 * Used for files exceeding LARGE_FILE_CHARS to keep total context within budget.
 */
function summarizeFile(content: string): string {
  const lines = content.split('\n');
  if (lines.length <= SUMMARY_HEAD_LINES + SUMMARY_TAIL_LINES) return content;
  const head = lines.slice(0, SUMMARY_HEAD_LINES);
  const tail = lines.slice(lines.length - SUMMARY_TAIL_LINES);
  const omitted = lines.length - SUMMARY_HEAD_LINES - SUMMARY_TAIL_LINES;
  return [...head, `\n[... ${omitted} líneas omitidas ...]`, ...tail].join('\n');
}

/**
 * @description Extracts bare filenames / relative paths referenced in the task template.
 * Used to boost priority for files the agent is expected to read.
 */
function extractFileReferences(template: string): Set<string> {
  const refs = new Set<string>();
  // Match patterns like `path/to/file.ext` or just `file.ext` in backticks or plain text
  const matches = template.matchAll(/`?([a-zA-Z0-9_\-./]+\.[a-zA-Z]{1,10})`?/g);
  for (const m of matches) {
    refs.add(m[1]);
  }
  return refs;
}

/**
 * @description Reads project_memory.md from the memory directory.
 * Returns empty string if file doesn't exist yet (early pipeline stages).
 */
async function readProjectMemory(projectDir: string): Promise<string> {
  try {
    return await fs.readFile(path.join(projectDir, 'memory', 'project_memory.md'), 'utf8');
  } catch {
    return '';
  }
}

/**
 * @description Reads a spec artifact (ambiguities.md, brainstorm.md) from the spec directory.
 * Returns empty string if file doesn't exist (e.g. pipeline hasn't reached spec-agent yet).
 */
async function readSpecArtifact(projectDir: string, filename: string): Promise<string> {
  try {
    return await fs.readFile(path.join(projectDir, 'spec', filename), 'utf8');
  } catch {
    return '';
  }
}

/**
 * @description Reads the execution-plan.md generated by the planner-agent (Layer 0).
 * Returns empty string if file doesn't exist yet.
 */
async function readExecutionPlan(projectDir: string): Promise<string> {
  try {
    return await fs.readFile(path.join(projectDir, 'plan', 'execution-plan.md'), 'utf8');
  } catch {
    return '';
  }
}

interface ContextOptions {
  projectId: string;
  projectDir: string;
  /** Set of layer numbers that have already completed — only these are injected as context */
  completedLayers: Set<number>;
  /** Skill task prompt template (will have {{FILES_LIST}} and {{SPEC}} replaced) */
  taskTemplate: string;
  /** Current layer number — used to inject layer-specific context (e.g. test-mapping.json for L7) */
  currentLayer?: number;
}

/**
 * @description Builds the full task prompt for an agent, injecting spec.md and
 * a summary of previously generated files from earlier layers.
 */
export async function buildTaskPrompt(opts: ContextOptions): Promise<string> {
  const { projectId, projectDir, completedLayers, taskTemplate, currentLayer } = opts;

  // 1. Read spec.md
  const specContent = await readSpecMd(projectDir);

  // 1.5. Read project_memory.md (always included — max priority)
  const projectMemory = await readProjectMemory(projectDir);
  const memorySection = projectMemory
    ? `\n\n## Project Memory (decisiones y patrones acumulados)\n${projectMemory}`
    : '';

  // 1.6. Read spec artifacts (ambiguities.md, brainstorm.md) for layers >= 1
  let specArtifactsSection = '';
  if (currentLayer !== undefined && currentLayer >= 1) {
    const ambiguities = await readSpecArtifact(projectDir, 'ambiguities.md');
    const brainstorm = await readSpecArtifact(projectDir, 'brainstorm.md');
    if (ambiguities) {
      specArtifactsSection += `\n\n## Ambiguities (supuestos del spec-agent)\n${ambiguities}`;
    }
    if (brainstorm) {
      specArtifactsSection += `\n\n## Brainstorm (decisiones arquitectónicas)\n${brainstorm}`;
    }
  }

  // 1.7. Read execution-plan.md (planner-agent output) for layers >= 1
  let executionPlanSection = '';
  if (currentLayer !== undefined && currentLayer >= 1) {
    const plan = await readExecutionPlan(projectDir);
    if (plan) {
      executionPlanSection = `\n\n## Execution Plan (generado por planner-agent)\n${plan}`;
    }
  }

  // 1.7. For integration agent (L7), inject criteriaMap + test-mapping.json if present
  let criteriaMapSection = '';
  let testMappingSection = '';
  if (currentLayer === 7) {
    const criteriaMap = extractCriteria(specContent);
    if (Object.keys(criteriaMap).length > 0) {
      criteriaMapSection = `\n\n## Criteria Map (extraído del spec)\n\`\`\`json\n${JSON.stringify(criteriaMap, null, 2)}\n\`\`\``;
    }

    try {
      const raw = await fs.readFile(path.join(projectDir, 'test-mapping.json'), 'utf8');
      testMappingSection = `\n\n## test-mapping.json (generado por QA agent)\n\`\`\`json\n${raw}\n\`\`\``;
    } catch { /* non-fatal — agent falls back to its own instructions */ }
  }

  // 2. Fetch all previously generated files (no count limit — budget controls inclusion)
  const priorFiles = await prisma.generatedFile.findMany({
    where: { projectId, layer: { in: [...completedLayers] } },
    orderBy: [{ layer: 'desc' }, { sizeBytes: 'desc' }],
    select: { path: true, sizeBytes: true, layer: true },
  });

  let filesContext = '';
  if (priorFiles.length > 0) {
    // Priority: files explicitly referenced in the task template first
    const refs = extractFileReferences(taskTemplate);
    const sorted = [
      ...priorFiles.filter((f) => refs.has(f.path) || [...refs].some((r) => f.path.endsWith(r))),
      ...priorFiles.filter((f) => !refs.has(f.path) && ![...refs].some((r) => f.path.endsWith(r))),
    ];

    let charsUsed = 0;
    const parts: string[] = ['\n\n## Archivos generados en capas anteriores\n'];
    const omittedPaths: string[] = [];

    for (const file of sorted) {
      if (charsUsed >= TOKEN_BUDGET_CHARS) {
        omittedPaths.push(file.path);
        continue;
      }
      const absPath = path.join(projectDir, file.path);
      try {
        const raw = await fs.readFile(absPath, 'utf8');
        const content = raw.length > LARGE_FILE_CHARS ? summarizeFile(raw) : raw;
        const remaining = TOKEN_BUDGET_CHARS - charsUsed;
        const snippet = content.slice(0, remaining);
        parts.push(`\n### ${file.path}\n\`\`\`\n${snippet}\n\`\`\``);
        charsUsed += snippet.length;
      } catch {
        parts.push(`\n- ${file.path} (no readable)`);
      }
    }

    if (omittedPaths.length > 0) {
      parts.push(`\n\n(${omittedPaths.length} archivos omitidos por presupuesto de contexto)`);
    }

    filesContext = parts.join('');
  } else if (completedLayers.size > 0) {
    // List files from filesystem as fallback
    const allFiles = await listAllFiles(projectDir, projectDir);
    if (allFiles.length > 0) {
      filesContext = `\n\n## Archivos del proyecto\n${allFiles.slice(0, 50).join('\n')}`;
    }
  }

  return taskTemplate
    .replace('{{SPEC}}', specContent + specArtifactsSection + executionPlanSection + memorySection + criteriaMapSection + testMappingSection)
    .replace('{{FILES_LIST}}', filesContext || '(sin archivos previos)');
}
