import fs from 'node:fs/promises';
import path from 'node:path';
import prisma from '../lib/prisma.js';

const MAX_CONTEXT_FILES = 20;
const MAX_FILE_CHARS = 80_000; // ~20K tokens of context for prior layers

/**
 * @description Reads a project's spec.md from the filesystem (generated by the spec engine).
 */
async function readSpecMd(projectDir: string): Promise<string> {
  try {
    return await fs.readFile(path.join(projectDir, 'spec.md'), 'utf8');
  } catch {
    try {
      return await fs.readFile(path.join(projectDir, 'README.md'), 'utf8');
    } catch {
      return '(no spec.md found)';
    }
  }
}

/**
 * @description Lists all files under `dir`, returning paths relative to rootDir.
 */
async function listAllFiles(dir: string, rootDir: string): Promise<string[]> {
  const result: string[] = [];
  try {
    const entries = await fs.readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      const abs = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        result.push(...(await listAllFiles(abs, rootDir)));
      } else {
        result.push(path.relative(rootDir, abs));
      }
    }
  } catch {
    // Directory may not exist yet
  }
  return result;
}

/**
 * @description Reads project_memory.md from the memory directory.
 * Returns empty string if file doesn't exist yet (early pipeline stages).
 */
async function readProjectMemory(projectDir: string): Promise<string> {
  try {
    return await fs.readFile(path.join(projectDir, 'memory', 'project_memory.md'), 'utf8');
  } catch {
    return '';
  }
}

interface ContextOptions {
  projectId: string;
  projectDir: string;
  /** Current layer number — files from layers < currentLayer are included in context */
  currentLayer: number;
  /** Skill task prompt template (will have {{FILES_LIST}} and {{SPEC}} replaced) */
  taskTemplate: string;
}

/**
 * @description Builds the full task prompt for an agent, injecting spec.md and
 * a summary of previously generated files from earlier layers.
 */
export async function buildTaskPrompt(opts: ContextOptions): Promise<string> {
  const { projectId, projectDir, currentLayer, taskTemplate } = opts;

  // 1. Read spec.md
  const specContent = await readSpecMd(projectDir);

  // 1.5. Read project_memory.md (always included — max priority)
  const projectMemory = await readProjectMemory(projectDir);
  const memorySection = projectMemory
    ? `\n\n## Project Memory (decisiones y patrones acumulados)\n${projectMemory}`
    : '';

  // 2. List all previously generated files (layers < currentLayer)
  const priorFiles = await prisma.generatedFile.findMany({
    where: { projectId, layer: { lt: currentLayer } },
    orderBy: [{ layer: 'asc' }, { path: 'asc' }],
    take: MAX_CONTEXT_FILES,
    select: { path: true, sizeBytes: true },
  });

  let filesContext = '';
  if (priorFiles.length > 0) {
    let charsUsed = 0;
    const parts: string[] = [`\n\n## Archivos generados en capas anteriores\n`];

    for (const file of priorFiles) {
      const absPath = path.join(projectDir, file.path);
      try {
        if (charsUsed < MAX_FILE_CHARS) {
          const content = await fs.readFile(absPath, 'utf8');
          const snippet = content.slice(0, MAX_FILE_CHARS - charsUsed);
          parts.push(`\n### ${file.path}\n\`\`\`\n${snippet}\n\`\`\``);
          charsUsed += snippet.length;
        } else {
          parts.push(`\n- ${file.path} (${file.sizeBytes} bytes — omitido por límite de contexto)`);
        }
      } catch {
        parts.push(`\n- ${file.path} (no readable)`);
      }
    }

    // If there are more files than we fetched, note it
    const total = await prisma.generatedFile.count({ where: { projectId, layer: { lt: currentLayer } } });
    if (total > MAX_CONTEXT_FILES) {
      parts.push(`\n\n(${total - MAX_CONTEXT_FILES} archivos adicionales omitidos)`);
    }

    filesContext = parts.join('');
  } else if (currentLayer > 1) {
    // List files from filesystem as fallback
    const allFiles = await listAllFiles(projectDir, projectDir);
    if (allFiles.length > 0) {
      filesContext = `\n\n## Archivos del proyecto\n${allFiles.slice(0, 50).join('\n')}`;
    }
  }

  return taskTemplate
    .replace('{{SPEC}}', specContent + memorySection)
    .replace('{{FILES_LIST}}', filesContext || '(sin archivos previos)');
}
