import fs from 'node:fs/promises';
import path from 'node:path';
import { z } from 'zod';
import prisma from '../lib/prisma.js';
import { getRedisClient } from '../lib/redis.js';
import { runAgent, type AgentRunResult } from './base-agent.js';
import { buildTaskPrompt } from './context-builder.js';
import { extractCriteria } from './criteria-extractor.js';
import { getNextLayers, AGENT_GRAPH } from './dependency-graph.js';
import type { LayerNode } from './dependency-graph.js';
import { getCriteriaCoverageThreshold, verifyCriteriaCoverage } from './quality-gate.js';
import { verifyBatchOutput } from './batch-verifier.js';
import { emitEvent, buildEvent } from '../websocket/ws.emitter.js';

import { fileURLToPath } from 'node:url';

const PAUSE_POLL_MS = 2000;
const MAX_QA_RERUNS = 2;

/** Zod schema for the test-mapping.json produced by the QA agent. */
const TestMappingSchema = z.object({
  mappings: z.array(
    z.object({
      criteriaId: z.string(),
      testFile: z.string().nullable(),
      testName: z.string().nullable(),
      type: z.enum(['unit', 'integration']).nullable(),
    }),
  ),
});

export type TestMapping = z.infer<typeof TestMappingSchema>;

/**
 * @description Reads and validates test-mapping.json generated by the QA agent.
 * Returns null (non-fatal) if the file is missing or invalid.
 */
async function readTestMapping(projectDir: string): Promise<TestMapping | null> {
  try {
    const raw = await fs.readFile(path.join(projectDir, 'test-mapping.json'), 'utf8');
    return TestMappingSchema.parse(JSON.parse(raw));
  } catch {
    return null;
  }
}

/** Reads spec.md and extracts HU acceptance criteria for the quality gate. */
async function readCriteriaMap(projectDir: string) {
  try {
    const specContent = await fs.readFile(path.join(projectDir, 'spec.md'), 'utf8');
    return extractCriteria(specContent);
  } catch {
    return {};
  }
}

/** Merges multi-attempt QA runs into a single aggregate result. */
function mergeAgentResults(base: AgentRunResult, next: AgentRunResult): AgentRunResult {
  return {
    success: base.success && next.success,
    summary: next.summary || base.summary,
    tokensInput: base.tokensInput + next.tokensInput,
    tokensOutput: base.tokensOutput + next.tokensOutput,
    filesCreated: [...new Set([...base.filesCreated, ...next.filesCreated])],
  };
}

/** Builds the retry instructions sent back to the QA agent after a failed quality gate. */
function buildQaRetryPrompt(
  baseTaskPrompt: string,
  missingCriteria: string[],
  coveragePercent: number,
  threshold: number,
  attempt: number,
  diagnosticContext?: { filesInvolved: string[] },
): string {
  const missingList = missingCriteria.length > 0
    ? missingCriteria.map((criterionId) => `- ${criterionId}`).join('\n')
    : '- (sin criterios identificados)';

  let diagnosticSection = '';
  if (diagnosticContext && diagnosticContext.filesInvolved.length > 0) {
    diagnosticSection = `\n\n### Archivos involucrados en el intento anterior\n${diagnosticContext.filesInvolved.map((f) => `- \`${f}\``).join('\n')}\n\nAnaliza estos archivos para identificar por qué los criterios no fueron cubiertos.`;
  }

  return `${baseTaskPrompt}\n\n## Quality Gate Retry ${attempt}/${MAX_QA_RERUNS}\nLa cobertura actual es ${coveragePercent}% y el mínimo requerido es ${threshold}%.\n\nCriterios aún no cubiertos:\n${missingList}${diagnosticSection}\n\nDebes agregar o ajustar tests para estos criterios y reescribir \`test-mapping.json\` antes de llamar \`taskComplete\`.`;
}

/**
 * Re-runs the QA layer when coverage is below threshold, up to MAX_QA_RERUNS.
 * Emits a quality:gate event on every evaluation.
 */
async function enforceQaQualityGate(params: {
  agentId: string;
  projectId: string;
  projectDir: string;
  systemPrompt: string;
  taskPrompt: string;
  batchSignal?: AbortSignal;
  initialResult: AgentRunResult;
  investigationSkill?: string;
}): Promise<AgentRunResult> {
  const { agentId, projectId, projectDir, systemPrompt, taskPrompt, batchSignal, initialResult, investigationSkill } = params;

  let aggregateResult = initialResult;

  for (let rerunCount = 0; rerunCount <= MAX_QA_RERUNS; rerunCount++) {
    const criteriaMap = await readCriteriaMap(projectDir);
    const testMapping = (await readTestMapping(projectDir)) ?? { mappings: [] };
    const threshold = getCriteriaCoverageThreshold();
    const coverage = verifyCriteriaCoverage(criteriaMap, testMapping, threshold);

    emitEvent(buildEvent('quality:gate', projectId, {
      agentType: 'qa-agent',
      layer: 4,
      message: `Criteria coverage ${coverage.coveragePercent}% (${coverage.covered}/${coverage.total})`,
      coveragePercent: coverage.coveragePercent,
      covered: coverage.covered,
      total: coverage.total,
      missing: coverage.missing,
      passed: coverage.passed,
      rerunCount,
      threshold,
    }));

    if (coverage.passed) {
      return aggregateResult;
    }

    if (rerunCount === MAX_QA_RERUNS) {
      // T028: Generate investigation report on max retries exhausted
      await generateInvestigationReport(projectDir, projectId, coverage.missing, coverage.coveragePercent, threshold);
      throw new Error(
        `Quality gate failed after ${MAX_QA_RERUNS} re-runs: ${coverage.coveragePercent}% coverage (threshold ${threshold}%). Missing criteria: ${coverage.missing.join(', ') || 'unknown'}`,
      );
    }

    // T026: Build diagnostic retry prompt with specific failure context
    const retryPrompt = buildQaRetryPrompt(
      taskPrompt,
      coverage.missing,
      coverage.coveragePercent,
      threshold,
      rerunCount + 1,
      { filesInvolved: aggregateResult.filesCreated },
    );

    // Inject investigation skill into retry system prompt when available
    const retrySystemPrompt = investigationSkill
      ? `${systemPrompt}\n\n---\n\n${investigationSkill}`
      : systemPrompt;

    const retryResult = await runAgent({
      agentId,
      projectId,
      agentType: 'qa-agent',
      layer: 4,
      systemPrompt: retrySystemPrompt,
      taskPrompt: retryPrompt,
      projectDir,
      batchSignal,
    });

    aggregateResult = mergeAgentResults(aggregateResult, retryResult);

    if (!retryResult.success) {
      return aggregateResult;
    }
  }

  return aggregateResult;
}

/**
 * T028: Generates investigation-report.md when QA retries are exhausted.
 * Persists to project dir and emits WebSocket event.
 */
async function generateInvestigationReport(
  projectDir: string,
  projectId: string,
  missingCriteria: string[],
  coveragePercent: number,
  threshold: number,
): Promise<void> {
  const criteriaList = missingCriteria.length > 0
    ? missingCriteria.map((c) => `### ${c}\n- **Hipótesis:** Criterio no cubierto después de ${MAX_QA_RERUNS} reintentos\n- **Recomendación:** Revisar implementación manualmente`).join('\n\n')
    : '### (sin criterios identificados)';

  const report = `# Investigation Report\n\n## Criterios no cubiertos\n${criteriaList}\n\n## Resumen\n- Cobertura alcanzada: ${coveragePercent}%\n- Umbral requerido: ${threshold}%\n- Reintentos ejecutados: ${MAX_QA_RERUNS}\n- Bloqueadores identificados: ${missingCriteria.join(', ') || 'ninguno identificado'}\n`;

  const reportDir = path.join(projectDir, 'qa');
  const reportPath = path.join(reportDir, 'investigation-report.md');

  try {
    await fs.mkdir(reportDir, { recursive: true });
    await fs.writeFile(reportPath, report, 'utf8');
  } catch { /* non-fatal */ }

  emitEvent(buildEvent('qa:investigation-report', projectId, {
    agentType: 'qa-agent',
    layer: 4,
    message: `Investigation report generated: qa/investigation-report.md`,
    reportPath: 'qa/investigation-report.md',
    missingCriteria,
    coveragePercent,
  }));
}

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const SKILLS_DIR = path.resolve(__dirname, '..', '..', '..', '..', 'skills');
const PROJECTS_BASE_DIR = path.resolve(
  process.env.PROJECTS_BASE_DIR ?? path.join(__dirname, '..', '..', '..', '..', 'projects'),
);

/**
 * @description Composes a complete agent system prompt by prepending shared skill files
 * before the agent-specific system.md content.
 * Order: conventions → anti-patterns → output-format → agent system.md
 */
export function composeSystemPrompt(sharedSkills: string[], agentSystemMd: string, extraSkills?: string[]): string {
  const allSkills = [...sharedSkills, ...(extraSkills ?? [])];
  if (allSkills.length === 0) return agentSystemMd;
  return [...allSkills, agentSystemMd].join('\n\n---\n\n');
}

/**
 * @description Loads all shared skill files from skills/_shared/ directory.
 * Must be called once per pipeline run (not per layer).
 * Order: conventions.md → anti-patterns.md → output-format.md
 */
export async function loadSharedSkills(): Promise<string[]> {
  const sharedFiles = ['conventions.md', 'anti-patterns.md', 'output-format.md'];
  return Promise.all(sharedFiles.map((f) => readSkillFile(`_shared/${f}`)));
}

/** TDD skill layers: backend-agent (2) and frontend-agent (3) */
export const TDD_LAYERS = new Set([2, 3]);

/**
 * @description Loads the TDD shared skill. Called once per pipeline run.
 */
export async function loadTddSkill(): Promise<string> {
  return readSkillFile('_shared/test-driven-development.md');
}

/**
 * @description Loads the investigating-test-failures skill for QA retries.
 */
export async function loadInvestigationSkill(): Promise<string> {
  return readSkillFile('_shared/investigating-test-failures.md');
}

const MAX_MEMORY_CHARS = 20_000; // ≈ 5000 tokens at 4 chars/token

/**
 * @description Appends a memory section for a completed agent layer to project_memory.md.
 * Creates the memory directory and file if they don't exist.
 * Caps the total file at MAX_MEMORY_CHARS by discarding oldest sections first.
 */
export async function appendProjectMemory(
  projectDir: string,
  layer: number,
  agentType: string,
  summary: string,
): Promise<void> {
  const memoryDir = path.join(projectDir, 'memory');
  const memoryFile = path.join(memoryDir, 'project_memory.md');

  await fs.mkdir(memoryDir, { recursive: true });

  let existing = '';
  try {
    existing = await fs.readFile(memoryFile, 'utf8');
  } catch {
    // File doesn't exist yet — start fresh
  }

  const section = `\n## Layer ${layer}: ${agentType}\n### Summary\n${summary.trim()}\n`;
  let combined = existing + section;

  // Cap at MAX_MEMORY_CHARS by removing oldest layer sections
  if (combined.length > MAX_MEMORY_CHARS) {
    const sections = combined.split(/\n(?=## Layer )/);
    while (combined.length > MAX_MEMORY_CHARS && sections.length > 1) {
      sections.shift(); // remove oldest section
      combined = sections.join('\n## Layer ');
    }
  }

  await fs.writeFile(memoryFile, combined, 'utf8');
}

/**
 * @description Resolves the absolute project directory for a projectId.
 */
export function getProjectDir(projectId: string): string {
  return path.resolve(PROJECTS_BASE_DIR, projectId);
}

/**
 * @description Reads a skill prompt file from the skills/ directory.
 */
async function readSkillFile(relativePath: string): Promise<string> {
  return fs.readFile(path.join(SKILLS_DIR, relativePath), 'utf8');
}

/**
 * @description Checks if the project has been signalled to pause via Redis flag.
 * The flag is a Redis key: `project:pause:{projectId}`
 */
async function isPaused(projectId: string): Promise<boolean> {
  const redis = getRedisClient();
  const val = await redis.get(`project:pause:${projectId}`);
  return val === '1';
}

/**
 * @description Waits until the pause flag is cleared or a timeout is reached.
 * Returns false if cancelled (pause never lifted after 1h).
 */
async function waitForResume(projectId: string): Promise<boolean> {
  const MAX_WAIT = 60 * 60 * 1000; // 1 hour
  const started = Date.now();
  while (Date.now() - started < MAX_WAIT) {
    await sleep(PAUSE_POLL_MS);
    if (!(await isPaused(projectId))) return true;
  }
  return false;
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * @description Writes the latest spec content from the DB into the project directory
 * so agents can read spec.md, data-model.md, and api-design.md via the readFile tool.
 */
async function materializeSpec(projectId: string, projectDir: string): Promise<void> {
  const spec = await prisma.projectSpec.findFirst({
    where: { projectId },
    orderBy: { version: 'desc' },
    select: { content: true },
  });
  if (!spec?.content) return;

  const content = spec.content as Record<string, string>;
  const files: [string, string | undefined][] = [
    ['spec.md', content.spec],
    ['data-model.md', content.dataModel],
    ['api-design.md', content.apiDesign],
  ];

  for (const [name, text] of files) {
    if (text && text.length > 0) {
      await fs.writeFile(path.join(projectDir, name), text, 'utf8');
    }
  }
}

/**
 * @description Main pipeline orchestrator.
 * Runs all 10 agent layers (planner + 9 generation agents) for a project.
 * On retry, skips layers whose agents are already completed in the DB.
 */
export async function runPipeline(projectId: string, _userId: string): Promise<void> {
  const projectDir = getProjectDir(projectId);

  // Ensure project directory exists
  await fs.mkdir(projectDir, { recursive: true });

  // Materialize spec files from DB into the project directory so agents can read them
  await materializeSpec(projectId, projectDir);

  // Load shared skills once for the entire pipeline (not per layer)
  const sharedSkills = await loadSharedSkills();
  const tddSkill = await loadTddSkill();
  const investigationSkill = await loadInvestigationSkill();

  // Build set of already-completed layers for retry support
  const completedAgents = await prisma.agent.findMany({
    where: { projectId, status: 'completed' },
    select: { layer: true },
  });
  const completedLayerNums = new Set<number>(completedAgents.map((a) => a.layer));

  // Update project status to 'running'
  await prisma.project.update({
    where: { id: projectId },
    data: { status: 'running' },
  });

  const totalLayers = AGENT_GRAPH.length;

  try {
    while (true) {
      const batch = getNextLayers(completedLayerNums);
      if (batch.length === 0) break;

      // Check pause before starting this batch
      if (await isPaused(projectId)) {
        const firstLayer = batch[0];
        const lastGenFile = await prisma.generatedFile.findFirst({
          where: { projectId },
          orderBy: { createdAt: 'desc' },
          select: { path: true },
        });
        emitEvent(buildEvent('project:paused', projectId, {
          agentType: firstLayer.type,
          layer: firstLayer.layer,
          layerName: firstLayer.type.replace('-agent', ''),
          lastFile: lastGenFile?.path ?? null,
        }));
        await prisma.project.update({ where: { id: projectId }, data: { status: 'paused' } });

        const resumed = await waitForResume(projectId);
        if (!resumed) {
          throw new Error('Pipeline cancelled: pause timeout exceeded');
        }

        await prisma.project.update({ where: { id: projectId }, data: { status: 'running' } });
        for (const layerDef of batch) {
          emitEvent(buildEvent('agent:started', projectId, { agentType: layerDef.type, layer: layerDef.layer, message: 'Resumed' }));
        }
      }

      // Run all batch layers in parallel — abort siblings on any failure or user pause
      const batchController = new AbortController();
      let pauseWatcherActive = true;

      // Pause watcher: polls Redis while batch runs; aborts batchController if user pauses
      void (async () => {
        while (pauseWatcherActive && !batchController.signal.aborted) {
          await sleep(PAUSE_POLL_MS);
          if (!pauseWatcherActive || batchController.signal.aborted) break;
          if (await isPaused(projectId)) {
            batchController.abort();
            break;
          }
        }
      })();

      try {
        await Promise.all(batch.map(async (layerDef: LayerNode) => {
          try {
            await runLayer(layerDef, {
              projectId,
              projectDir,
              sharedSkills,
              tddSkill,
              investigationSkill,
              completedLayers: new Set(completedLayerNums),
              batchSignal: batchController.signal,
            });
          } catch (err) {
            batchController.abort();
            throw err;
          }
        }));
      } finally {
        pauseWatcherActive = false;
      }

      // If pause was triggered during batch, wait for resume before continuing
      if (await isPaused(projectId)) {
        emitEvent(buildEvent('project:paused', projectId, {
          agentType: batch[0].type,
          layer: batch[0].layer,
          layerName: batch[0].type.replace('-agent', ''),
          lastFile: null,
        }));
        await prisma.project.update({ where: { id: projectId }, data: { status: 'paused' } });
        const resumed = await waitForResume(projectId);
        if (!resumed) {
          throw new Error('Pipeline cancelled: pause timeout exceeded');
        }
        await prisma.project.update({ where: { id: projectId }, data: { status: 'running' } });
      }

      // Mark all batch layers as completed
      for (const layerDef of batch) {
        completedLayerNums.add(layerDef.layer);
      }

      // Update progress after each batch
      const pipelineProgress = Math.round((completedLayerNums.size / totalLayers) * 100);
      const lastLayer = batch.at(-1);
      if (!lastLayer) {
        continue;
      }
      await prisma.project.update({
        where: { id: projectId },
        data: { progress: pipelineProgress, currentLayer: lastLayer.layer },
      });
    }

    // All layers done
    await prisma.project.update({
      where: { id: projectId },
      data: { status: 'done', progress: 100 },
    });

    emitEvent(buildEvent('project:done', projectId, { progress: 100 }));
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);

    await prisma.project.update({
      where: { id: projectId },
      data: { status: 'error', errorMessage: message },
    });

    emitEvent(buildEvent('project:error', projectId, { message }));
    throw err;
  }
}

interface RunLayerContext {
  projectId: string;
  projectDir: string;
  sharedSkills: string[];
  /** TDD shared skill content — injected for layers in TDD_LAYERS */
  tddSkill: string;
  /** Investigation skill content — injected for QA retry prompts */
  investigationSkill: string;
  /** Layers completed before this batch started — passed to context-builder for parallel-safe injection */
  completedLayers: Set<number>;
  /** Abort signal from the batch AbortController — fired when a sibling parallel agent fails */
  batchSignal?: AbortSignal;
}

/**
 * @description Runs a single agent layer end-to-end: upsert agent record, build prompts,
 * execute runAgent, track files, append memory, emit progress.
 */
async function runLayer(layerDef: LayerNode, ctx: RunLayerContext): Promise<void> {
  const { projectId, projectDir, sharedSkills, tddSkill, investigationSkill, completedLayers, batchSignal } = ctx;

  // Get or create agent record
  const agent = await prisma.agent.upsert({
    where: { uq_agents_project_type: { projectId, type: layerDef.type } },
    create: {
      projectId,
      type: layerDef.type,
      layer: layerDef.layer,
      status: 'running',
      startedAt: new Date(),
    },
    update: {
      status: 'running',
      progress: 0,
      error: null,
      startedAt: new Date(),
      completedAt: null,
    },
  });

  // Read skill prompts and compose with shared skills
  const agentSystemMd = await readSkillFile(layerDef.systemFile);
  const extraSkills = TDD_LAYERS.has(layerDef.layer) ? [tddSkill] : undefined;
  const systemPrompt = composeSystemPrompt(sharedSkills, agentSystemMd, extraSkills);
  const taskTemplate = await readSkillFile(layerDef.taskFile);

  // Build task prompt with context from prior layers
  const taskPrompt = await buildTaskPrompt({
    projectId,
    projectDir,
    completedLayers,
    taskTemplate,
    currentLayer: layerDef.layer,
  });

  // Run the agent
  let result = await runAgent({
    agentId: agent.id,
    projectId,
    agentType: layerDef.type,
    layer: layerDef.layer,
    systemPrompt,
    taskPrompt,
    projectDir,
    batchSignal,
  });

  if (layerDef.layer === 4 && result.success) {
    result = await enforceQaQualityGate({
      agentId: agent.id,
      projectId,
      projectDir,
      systemPrompt,
      taskPrompt,
      batchSignal,
      initialResult: result,
      investigationSkill,
    });
  }

  // Track generated files in DB
  if (result.filesCreated.length > 0) {
    await Promise.allSettled(
      result.filesCreated.map(async (filePath) => {
        const absPath = path.join(projectDir, filePath);
        let size = 0;
        try {
          const stat = await fs.stat(absPath);
          size = stat.size;
        } catch { /* file may have been removed */ }

        await prisma.generatedFile.upsert({
          where: { uq_generated_files_project_path: { projectId, path: filePath } },
          create: {
            projectId,
            agentId: agent.id,
            name: path.basename(filePath),
            path: filePath,
            sizeBytes: size,
            layer: layerDef.layer,
          },
          update: {
            agentId: agent.id,
            sizeBytes: size,
          },
        }).catch(() => { /* non-fatal */ });
      }),
    );
  }

  // Verify layer output (post-agent checkpoint)
  let planContent: string | undefined;
  try {
    planContent = await fs.readFile(path.join(projectDir, 'plan', 'execution-plan.md'), 'utf8');
  } catch { /* plan may not exist */ }

  const verification = await verifyBatchOutput(layerDef, projectDir, planContent);

  // Persist checkpoint in DB (non-fatal)
  try {
    await prisma.verificationCheckpoint.create({
      data: {
        projectId,
        layer: layerDef.layer,
        agentType: layerDef.type,
        status: verification.status,
        details: verification.details as unknown as import('@prisma/client').Prisma.InputJsonValue,
      },
    });
  } catch { /* non-fatal — model may not exist yet */ }

  emitEvent(buildEvent('checkpoint:result', projectId, {
    layer: layerDef.layer,
    agentType: layerDef.type,
    status: verification.status,
    details: verification.details,
  }));

  if (verification.status === 'fail') {
    await prisma.project.update({
      where: { id: projectId },
      data: { status: 'paused', errorMessage: `Verification failed for ${layerDef.type}: ${verification.details.map((d) => d.message).join('; ')}` },
    });
    emitEvent(buildEvent('project:paused', projectId, {
      reason: 'verification_failure',
      layer: layerDef.layer,
      details: verification.details,
    }));
    throw new Error(`Verification CRITICAL failure for ${layerDef.type}`);
  }

  // Append layer completion to project memory (non-fatal)
  appendProjectMemory(projectDir, layerDef.layer, layerDef.type, result.summary).catch(() => { /* non-fatal */ });

  emitEvent(buildEvent('agent:completed', projectId, {
    agentType: layerDef.type,
    layer: layerDef.layer,
    tokensUsed: result.tokensInput + result.tokensOutput,
    filesCount: result.filesCreated.length,
  }));

  // Emit plan:generated after planner-agent (Layer 0) completes
  if (layerDef.layer === 0) {
    let planContent = '';
    try {
      planContent = await fs.readFile(path.join(projectDir, 'plan', 'execution-plan.md'), 'utf8');
    } catch { /* non-fatal — plan may not have been written */ }
    emitEvent(buildEvent('plan:generated', projectId, {
      message: planContent || 'Execution plan generated',
    }));
  }
}
