/**
 * Quality gate for HU acceptance criteria coverage verification.
 * Determines if the QA output covers enough acceptance criteria to pass.
 */
import type { CriteriaMap } from './criteria-extractor.js';
import type { TestMapping } from './orchestrator.js';

const DEFAULT_THRESHOLD = 80;

/** Returns the configured criteria coverage threshold from the environment. */
export function getCriteriaCoverageThreshold(): number {
  const parsed = Number.parseInt(
    process.env.CRITERIA_COVERAGE_THRESHOLD ?? `${DEFAULT_THRESHOLD}`,
    10,
  );
  return Number.isNaN(parsed) ? DEFAULT_THRESHOLD : parsed;
}

/** Result of running the quality gate. */
export interface CoverageResult {
  /** Percentage of criteria covered (0–100). */
  coveragePercent: number;
  /** Number of criteria with at least one mapped test. */
  covered: number;
  /** Total number of criteria across all HUs. */
  total: number;
  /** CriteriaIds without any test mapping. */
  missing: string[];
  /** Whether coveragePercent >= threshold. */
  passed: boolean;
}

/**
 * Verifies that the test mapping covers enough acceptance criteria.
 *
 * @param criteriaMap - Parsed HU criteria from the spec
 * @param testMapping - JSON output generated by the QA agent
 * @param threshold   - Minimum coverage percentage required (default: 80)
 * @returns CoverageResult with coverage stats and pass/fail status
 */
export function verifyCriteriaCoverage(
  criteriaMap: CriteriaMap,
  testMapping: TestMapping,
  threshold = getCriteriaCoverageThreshold(),
): CoverageResult {
  const allIds = Object.values(criteriaMap).flatMap((hu) =>
    hu.criteria.map((c) => c.id),
  );
  const total = allIds.length;

  if (total === 0) {
    return { coveragePercent: 100, covered: 0, total: 0, missing: [], passed: true };
  }

  const coveredSet = new Set(
    testMapping.mappings
      .filter((m) => m.testFile !== null)
      .map((m) => m.criteriaId),
  );

  const covered = allIds.filter((id) => coveredSet.has(id)).length;
  const missing = allIds.filter((id) => !coveredSet.has(id));
  const coveragePercent = Math.round((covered / total) * 100);

  return { coveragePercent, covered, total, missing, passed: coveragePercent >= threshold };
}
